### ISSUE TITLE
(r0.0.9) - Unable to create NEW world

### ISSUE THREAD

**Issue by Tursiops-G** [Treppord/PSWG-Adventures-EP1#1]
Using release 0.0.9, Unable to create NEW world:
Logdump:  https://paste.ee/p/rvTZw

**Comment by Tursiops-G** [comment]
Fixed in release 0.0.10.1

**Comment by Treppord** [comment]
:D

**Comment by Tursiops-G** [comment]
Seems that:

 java.lang.RuntimeException: Failed to get element ResourceKey[minecraft:worldgen/noise_settings / ad_astra:orbit]; Failed to get element ResourceKey[minecraft:worldgen/biome / ad_astra:orbit]

Also applied when one Doesn't even HAVE Ad Astra installed...
:D
